### ISSUE TITLE
Move altcampus.io blog to altcampus.school

### ISSUE THREAD

**Issue by nnnkit** [prank7/altcampus.school#37]
Move all the blogs from altcampus.io/blog to altcampus.school/community/post

**Comment by prank7** [comment]
Please make sure to add canonical link in .io's website for these links. Then after a month we can remove the blog fully.

The original posts for these would be .school's blog. .io will point to them as canonical links.

Read this - https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls if need more clarity on canonical links

**Comment by nnnkit** [comment]
Yes, I'll do that.

**Comment by nnnkit** [comment]
#46
